// @generated by midnight-builder; do not edit.
export const generatedAnimationTokens = [
  "b93b8b057093721b",
  "dd9c8c4173d85d74",
  "c91ebdf8072e334d",
  "2d4128c607c05058",
  "55ec0e52f84818e4",
  "f948fe5c9293249c",
] as const;
export const generatedFlagAnimationToken = "2d4128c607c05058";
