import{interactionKey,requestAnimation}from"../lib/stellar-client";import{CanvasRenderer}from"../lib/canvas-renderer";import type{StellarAnimation}from"../lib/stellar-container";
export class StellarGifPlayer{
  element=document.createElement("section");canvas=document.createElement("canvas");animation:StellarAnimation|null=null;onLoaded?:(animation:StellarAnimation)=>void;
  private renderer:CanvasRenderer;private frame=0;private timer=0;private playing=false;private looped=false;private gesture=0;private unlocked=false;private button=document.createElement("button");
  constructor(private name:string,compact=false,alt="Animated fan archive image"){this.element.className=`stellar-player${compact?" compact":""}`;this.canvas.setAttribute("aria-label",alt);this.canvas.setAttribute("role","img");this.renderer=new CanvasRenderer(this.canvas);const stage=document.createElement("div");stage.className="player-stage";stage.innerHTML=`<p class="loading-copy">Loading animation…</p>`;stage.append(this.canvas);this.button.className="media-toggle";this.button.type="button";this.button.setAttribute("aria-label","Pause animation");this.button.textContent="Ⅱ";this.button.addEventListener("click",()=>this.toggle());stage.append(this.button);this.element.append(stage);this.load()}
  private async load(){try{this.animation=await requestAnimation(this.name);this.renderer.resize(this.animation.width,this.animation.height);this.element.classList.add("loaded");this.render();this.play(false);this.onLoaded?.(this.animation)}catch(error){this.element.classList.add("player-error");console.error(error)}}
  private render(){if(!this.animation)return;this.frame%=this.animation.frames.length;const frame=this.animation.frames[this.frame];this.renderer.draw(frame.rgba,this.animation.width,this.animation.height)}
  private tick=()=>{if(!this.playing||!this.animation)return;this.render();const delay=Math.max(20,this.animation.frames[this.frame].delay*10);this.frame=(this.frame+1)%this.animation.frames.length;if(this.frame===0){this.looped=true;void this.tryUnlock()}this.timer=window.setTimeout(this.tick,delay)};
  private async tryUnlock(){if(this.unlocked||!this.looped||this.gesture!==3||!this.animation)return;this.unlocked=true;const wasPlaying=this.playing;this.pause(false);try{this.animation=await requestAnimation(this.name,interactionKey(this.animation,this.name));this.frame=this.animation.frames.length-1;this.render();if(wasPlaying)this.play(false)}catch(error){this.unlocked=false;console.error(error)}}
  play(user=true){if(this.playing)return;if(user&&(this.gesture&1))this.gesture|=2;this.playing=true;this.button.textContent="Ⅱ";this.button.setAttribute("aria-label","Pause animation");this.tick();void this.tryUnlock()}
  pause(user=true){this.playing=false;clearTimeout(this.timer);if(user)this.gesture|=1;this.button.textContent="▶";this.button.setAttribute("aria-label","Play animation")}
  toggle(){this.playing?this.pause(true):this.play(true)}destroy(){this.pause(false)}
}
