services:
  blueprint:
    build:
      context: .
      dockerfile: src/docker/Dockerfile
    restart: on-failure
    ports:
      - "8011:8011"
    environment:
      GZCTF_FLAG: "HOLOGY9{local_compose_flag}"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
        reservations:
          cpus: "0.25"
          memory: "128M"
