// @generated by midnight-builder; do not edit.
pub(super) struct EncryptedAsset { pub token: u64, pub bytes: &'static [u8] }
pub(super) static ENCRYPTED_ASSETS: &[EncryptedAsset] = &[
    EncryptedAsset { token: 0xb93b8b057093721b, bytes: include_bytes!("../../../../app/src/assets/vault/b93b8b057093721b.stlr") },
    EncryptedAsset { token: 0xdd9c8c4173d85d74, bytes: include_bytes!("../../../../app/src/assets/vault/dd9c8c4173d85d74.stlr") },
    EncryptedAsset { token: 0xc91ebdf8072e334d, bytes: include_bytes!("../../../../app/src/assets/vault/c91ebdf8072e334d.stlr") },
    EncryptedAsset { token: 0x2d4128c607c05058, bytes: include_bytes!("../../../../app/src/assets/vault/2d4128c607c05058.stlr") },
    EncryptedAsset { token: 0x55ec0e52f84818e4, bytes: include_bytes!("../../../../app/src/assets/vault/55ec0e52f84818e4.stlr") },
    EncryptedAsset { token: 0xf948fe5c9293249c, bytes: include_bytes!("../../../../app/src/assets/vault/f948fe5c9293249c.stlr") },
];
