defaults
{
    instances = 64
    log_type = SYSLOG daemon info
    log_on_success = HOST PID
    log_on_failure = HOST
    cps = 100 10
}

service suiwallet
{
    type = UNLISTED
    socket_type = stream
    protocol = tcp
    port = 9999
    wait = no
    user = suiwallet
    server = /usr/local/bin/service.sh
    disable = no
    per_source = 2
}
