#!/usr/bin/env python3
"""Regenerate the native encrypted reward blob from the author-side secret."""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "native/reward_blob.h"
FLAG_TEXT = "HOLOGY9{5u1g0tch1_h1dd3n_c0m3t_r1tu4l_9f3a7c2e}"
MASK64 = (1 << 64) - 1
GOLDEN = 0x9E3779B97F4A7C15
HASH_SALT = 0xA7


def mix64(value: int) -> int:
    value &= MASK64
    value ^= value >> 30
    value = (value * 0xBF58476D1CE4E5B9) & MASK64
    value ^= value >> 27
    value = (value * 0x94D049BB133111EB) & MASK64
    value ^= value >> 31
    return value & MASK64


def rotl8(value: int, distance: int) -> int:
    value &= 0xFF
    return ((value << distance) | (value >> (8 - distance))) & 0xFF


def initial_state() -> list[int]:
    state = [50, 50, 50, 0, 0, 0]
    packed = state[0] | (state[1] << 8) | (state[2] << 16)
    state[5] = mix64(0x535549474F544348 ^ packed)
    return state


def apply_action(state: list[int], action: int) -> None:
    hunger, bath, fun_value, mood, tick, care_hash = state
    if action == 1:
        hunger += 7
        bath -= 3
        fun_value -= 2
        mood ^= 0x13
    elif action == 2:
        bath += 11
        hunger -= 4
        fun_value -= 1
        mood ^= 0x37
    elif action == 3:
        fun_value += 13
        hunger -= 6
        bath -= 5
        mood ^= 0x51
    elif action == 4:
        hunger -= 2
        bath -= 2
        fun_value -= 2
        mood = rotl8(mood, 3)
    elif action == 5:
        fun_value ^= 0x5A
        hunger += 3
        bath ^= 0x95
        mood += 17
    elif action == 6:
        bath ^= 0xBB
        fun_value += 9
        mood ^= 0xA5
    elif action == 7:
        hunger ^= 0x1D
        bath += 4
        fun_value += 41
        mood ^= 0xFC
    else:
        raise ValueError(f"unknown care action {action}")

    hunger &= 0xFF
    bath &= 0xFF
    fun_value &= 0xFF
    mood &= 0xFF
    tick = (tick + 1) & 0xFFFFFFFF
    care_hash = mix64(
        care_hash
        ^ hunger
        ^ (bath << 8)
        ^ (fun_value << 16)
        ^ (mood << 24)
        ^ (action << 32)
        ^ (tick << 40)
    )
    state[:] = [hunger, bath, fun_value, mood, tick, care_hash]


def ritual_state() -> list[int]:
    state = initial_state()
    for action in (6, 1, 3, 7, 2, 5, 3, 6):
        apply_action(state, action)
    return state


def encrypted_reward(state: list[int]) -> bytes:
    hunger, bath, fun_value, mood, tick, care_hash = state
    seed = (
        mix64(care_hash)
        ^ mix64((hunger << 24) | (bath << 16) | (fun_value << 8) | mood)
        ^ mix64(tick)
    )
    result = bytearray()
    for index, plain in enumerate(FLAG_TEXT.encode("ascii")):
        seed = mix64(seed + index + GOLDEN)
        result.append(plain ^ (seed & 0xFF))
    return bytes(result)


def decrypt_reward(cipher: bytes, state: list[int]) -> bytes:
    hunger, bath, fun_value, mood, tick, care_hash = state
    seed = (
        mix64(care_hash)
        ^ mix64((hunger << 24) | (bath << 16) | (fun_value << 8) | mood)
        ^ mix64(tick)
    )
    output = bytearray()
    for index, encrypted in enumerate(cipher):
        seed = mix64(seed + index + GOLDEN)
        output.append(encrypted ^ (seed & 0xFF))
    return bytes(output)


def fmt_bytes(data: bytes) -> str:
    lines = []
    for start in range(0, len(data), 12):
        row = data[start : start + 12]
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in row))
    return ",\n".join(lines)


def main() -> None:
    state = ritual_state()
    if state[:5] != [39, 187, 74, 201, 8]:
        raise SystemExit(f"transition constants miss the intended byte state: {state[:5]}")
    cipher = encrypted_reward(state)
    if decrypt_reward(cipher, state) != FLAG_TEXT.encode("ascii"):
        raise SystemExit("reward stream self-check failed")
    hash_bytes = state[5].to_bytes(8, "little")
    hidden_hash = bytes(value ^ ((HASH_SALT + index * 19) & 0xFF) for index, value in enumerate(hash_bytes))
    content = f'''// Generated by scripts/encrypt_flag.py. Keep the author flag out of packaged assets.
#pragma once

#include <cstddef>
#include <cstdint>

namespace reward_blob {{
static constexpr std::uint8_t kCipher[] = {{
{fmt_bytes(cipher)}
}};
static constexpr std::size_t kCipherSize = sizeof(kCipher);
static constexpr std::uint8_t kHashBlob[8] = {{
{fmt_bytes(hidden_hash)}
}};
static constexpr std::uint8_t kHashSalt = 0x{HASH_SALT:02x};
}}  // namespace reward_blob
'''
    HEADER.write_text(content, encoding="utf-8")
    print(f"Wrote {HEADER.relative_to(ROOT)}")
    print(f"initial careHash=0x{initial_state()[5]:016x}")
    print(
        "ritual state: "
        f"hunger={state[0]} bath={state[1]} fun={state[2]} mood={state[3]} tick={state[4]} "
        f"careHash=0x{state[5]:016x}"
    )


if __name__ == "__main__":
    main()
