#!/usr/bin/env python3
"""Generate src/core/Tables.cs - the SBOX, the TARGET and the VM bytecode.

Forward transform, one byte at a time, with the state chained through:

    t     = SBOX[ rol8((input[i] ^ state) ^ K[i % len(K)], 3) ]
    state = t
    require t == TARGET[i]

Because `state` becomes TARGET[i] on a correct input, the whole thing
inverts without any search:

    prev    = STATE0 if i == 0 else TARGET[i-1]
    flag[i] = ror8(SBOX_INV[TARGET[i]], 3) ^ K[i % len(K)] ^ prev

  usage: emit.py <flag.txt> <out/Tables.cs>
"""
import sys

K = b"IL_15_4_l13"
STATE0 = 0xA7
ROT = 3

# opcodes
PUSH_IMM = 0x11
PUSH_IN = 0x12
PUSH_ST = 0x13
XOR = 0x21
ADD = 0x22          # implemented by the VM, never emitted
ROL = 0x23
SBOX_OP = 0x24
STORE_ST = 0x31
CMP = 0x32
LEN = 0x41
HALT = 0xFF


def make_sbox():
    """Fisher-Yates over identity, driven by a fixed-seed LCG."""
    x = 0x1BADB002
    s = list(range(256))
    for i in range(255, 0, -1):
        x = (x * 1103515245 + 12345) & 0xFFFFFFFF
        j = (x >> 16) % (i + 1)
        s[i], s[j] = s[j], s[i]
    return s


def rol8(v, n):
    n &= 7
    return ((v << n) | (v >> (8 - n))) & 0xFF if n else v & 0xFF


def ror8(v, n):
    n &= 7
    return ((v >> n) | (v << (8 - n))) & 0xFF if n else v & 0xFF


def transform(flag, sbox):
    state = STATE0
    target = []
    for i, ch in enumerate(flag):
        t = sbox[rol8((ch ^ state) ^ K[i % len(K)], ROT)]
        state = t
        target.append(t)
    return bytes(target)


def invert(target, sbox):
    sbox_inv = [0] * 256
    for i, v in enumerate(sbox):
        sbox_inv[v] = i
    out = []
    for i in range(len(target)):
        prev = STATE0 if i == 0 else target[i - 1]
        out.append(ror8(sbox_inv[target[i]], ROT) ^ K[i % len(K)] ^ prev)
    return bytes(out)


def emit_code(n):
    code = [LEN, n]
    for i in range(n):
        code += [
            PUSH_IN, i,
            PUSH_ST,
            XOR,
            PUSH_IMM, K[i % len(K)],
            XOR,
            ROL, ROT,
            SBOX_OP,
            STORE_ST,
            PUSH_ST,
            CMP, i,
        ]
    code.append(HALT)
    return bytes(code)


def csharp_array(name, data, per_line=16):
    lines = []
    for off in range(0, len(data), per_line):
        chunk = data[off:off + per_line]
        lines.append("            " + " ".join("0x{:02X},".format(b) for b in chunk))
    return (
        "        internal static readonly byte[] {} =\n"
        "        {{\n{}\n        }};\n".format(name, "\n".join(lines))
    )


TEMPLATE = """// <auto-generated> emitted by src/packer/emit.py - do not edit by hand </auto-generated>

namespace Core
{{
    /// <summary>Data tables consumed by <see cref="Machine"/>.</summary>
    internal static class Tables
    {{
        internal const byte STATE0 = 0x{state0:02X};

{sbox}
{k}
{target}
{code}    }}
}}
"""


def main():
    if len(sys.argv) != 3:
        print("usage: emit.py <flag.txt> <Tables.cs>", file=sys.stderr)
        return 2
    flag_path, out_path = sys.argv[1], sys.argv[2]

    with open(flag_path, "rb") as fh:
        flag = fh.read().strip()

    sbox = make_sbox()
    assert sorted(sbox) == list(range(256)), "SBOX is not a permutation"

    target = transform(flag, sbox)
    assert invert(target, sbox) == flag, "transform does not invert"
    assert flag not in target, "flag leaked into TARGET"

    code = emit_code(len(flag))

    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(TEMPLATE.format(
            state0=STATE0,
            sbox=csharp_array("SBOX", bytes(sbox)),
            k=csharp_array("K", K),
            target=csharp_array("TARGET", target),
            code=csharp_array("CODE", code),
        ))

    print("[+] wrote {}: {} flag bytes, {} code bytes".format(
        out_path, len(flag), len(code)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
